version: '3.4'



services:
  djangoapp:
    image: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - key.env
  db:
    env_file:
      - key.env
    environment:
      - DB_PASSWORD=${PASSWORD}
      - DB_USER=${USER}
      - DB_NAME=${NAME}
      - DB_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    image: postgres


  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - djangoapp
