version: '3.4'

services:
  djangoapp:
    image: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
