version: '3.4'

services:
  db:
    image: postgres
    env_file:
      - key.env
    # volumes:
    # - db-data:/var/lib/postgresql/data"""
  djangoapp:
    image: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - key.env

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - djangoapp

