version: '3.4'

services:
  djangoapp:
    image: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    
  db:
    image: "postgres"
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=digipm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
